name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: true

  build_deploy:
    name: Build and publish app
    needs: [ prepare_release ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Update version in package.json
        run: |
          npm version ${GITHUB_REF_NAME:1} --allow-same-version --git-tag-version=false

      - name: Create bundle
        run: scripts/create-bundle.sh

      - name: Add Release artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          fail_on_unmatched_files: false
          files: |
            _releases/psitransfer-*.tar.gz

  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [ build_deploy ]
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Create Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: "COMMIT"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                  "title": "## Features",
                  "labels": ["feat"]
                },
                {
                  "title": "## Performance",
                  "labels": ["perf"]
                },
                {
                  "title": "## Fixes",
                  "labels": ["fix", "bug"]
                },
                {
                  "title": "## Maintenance",
                  "labels": ["chore", "refactor", "cleanup"]
                },
                {
                  "title": "## Build",
                  "labels": ["build", "ci"]
                },
                {
                  "title": "## Documentation",
                  "labels": ["docs"]
                },
                {
                  "title": "## Tests",
                  "labels": ["test"]
                },
                {
                  "title": "## Reverts",
                  "labels": ["revert"]
                },
                {
                  "title": "## Styling",
                  "labels": ["style"]
                },
                {
                  "title": "## Dependencies",
                  "labels": ["deps"]
                },
                {
                  "title": "## Other Changes",
                  "labels": []
                }
              ],
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|bug|perf|cleanup|refactor|revert|style|test|deps){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ],
              "pr_template": "- [#{{TITLE}}](https://github.com/${{ github.repository }}/commit/#{{MERGE_SHA}}) by @#{{AUTHOR}}"
            }

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          body: ${{steps.build_changelog.outputs.changelog}}

  build_docker:
    name: Docker build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: psitrax
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        env:
          DOCKER_TAG: latest
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            psitrax/psitransfer:${{ github.ref_name }}
            ghcr.io/psi-4ward/psitransfer:${{ github.ref_name }}

  npm_publish:
    name: NPM publish
    runs-on: ubuntu-latest
    needs: [ publish_release, build_docker ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Install Node.js and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Update version in package.json
        run: |
          npm version ${GITHUB_REF_NAME:1} --allow-same-version --git-tag-version=false

      - name: Create bundle
        run: scripts/create-bundle.sh

      - name: NPM deploy
        run: |
          cd _releases
          mkdir _pkg
          cd _pkg
          tar xzf ../psitransfer-$GITHUB_REF_NAME.tar.gz --strip 1
          npm publish --provenance
          cd ../..
